'use strict';
// Write godot/data/antagonist-manifest.json from the MANIFEST of
// public/ludus/ludus-antagonist-factory.js, so the headset shows the
// same variant of a passion as the web game (PassionCore.sprite_for).
// Usage: node scripts/godot/export_antagonist_manifest.js

const fs = require('fs');
const path = require('path');
const F = require('../../public/ludus/ludus-antagonist-factory.js');

const root = path.join(__dirname, '..', '..');
fs.writeFileSync(path.join(root, 'godot/data/antagonist-manifest.json'),
  JSON.stringify({ note: 'Generated by scripts/godot/'
    + 'export_antagonist_manifest.js; do not edit.', manifest: F.MANIFEST })
    + '\n');
const files = F.MANIFEST.flatMap((o) => o.variants.map((v) => v.file));
console.log(`antagonist manifest: ${F.MANIFEST.length} objects, `
  + `${files.length} sprites`);
