'use strict';
// Write godot/tests/journal_fixture.json from public/ludus/ludus-journal.js
// and ludus-actions.js: the exported Markdown page of the journal, the
// reference for JournalCore.to_markdown.  Each record keeps its inputs
// (form, actions, passions, date), so the GDScript side replays the very
// same page and compares it letter for letter.
// Usage: node scripts/godot/make_journal_fixture.js

const fs = require('fs');
const path = require('path');
const A = require('../../public/ludus/ludus-actions.js');
const J = require('../../public/ludus/ludus-journal.js');

const root = path.join(__dirname, '..', '..');
const passionData = require(path.join(root, 'public/ludus/data/passions.json'));
const form = (w, rest) => Object.assign({ wisdom: w, faith: 1,
  dexterity: 1, constitution: 1, charisma: 1, cunning: 1, erudition: 1 },
rest || {});
const clone = (o) => JSON.parse(JSON.stringify(o));

// A rule of prayer that touches every kind of practice: counts, daily
// acts (one and several days), timers, the secret deed and a gate
// opened by the whole ladder.
function busy() {
  let a = A.normalize({});
  for (let i = 0; i < 33; i++) {
    a = A.prayKnot(a);
  }
  ['theodora', 'elder_sergius', 'abba_john', 'sister_catherine']
    .forEach((m) => { a = A.recordMeeting(a, m); });
  a = A.keepFast(a, '2026-09-29');
  a = A.addStillness(a, 61);
  a = A.doPractice(a, 'prostrations');
  a = A.doPractice(a, 'prostrations');
  a = A.doPractice(a, 'vigil', { minutes: 10 });
  a = A.doPractice(a, 'handiwork', { minutes: 4 });
  a = A.doPractice(a, 'alms', { day: '2026-09-29' });
  a = A.doPractice(a, 'forgive', { day: '2026-09-29' });
  a = A.doPractice(a, 'forgive', { day: '2026-09-30' });
  a = A.doPractice(a, 'secret_deed', { day: '2026-09-30' });
  ['contemplative', 'mystical'].forEach((g) => {
    a = A.acceptGift(a, form(14), g);
  });
  return a;
}

const cases = [
  { name: 'empty', form: {}, actions: {}, passions: {},
    date: '2026-09-30' },
  { name: 'guest', form: form(1), actions: A.normalize({}), passions: {},
    date: '2026-01-02' },
  { name: 'first-step', form: form(4, { faith: 3 }),
    actions: (() => {
      let a = A.normalize({});
      for (let i = 0; i < 10; i++) {
        a = A.prayKnot(a);
      }
      return A.recordMeeting(a, 'theodora');
    })(),
    passions: { gluttony: { meetings: 1, overcome: 0, captive: 1,
      discerned: false } },
    date: '2026-09-30' },
  { name: 'busy', form: form(12, { faith: 7, erudition: 5, cunning: 0 }),
    actions: busy(),
    passions: {
      gluttony: { meetings: 2, overcome: 1, captive: 1, discerned: true },
      anger: { meetings: 1, overcome: 1, captive: 0, discerned: false },
      pride: { meetings: 3, overcome: 0, captive: 3, discerned: false },
    },
    date: '2026-09-30' },
  { name: 'tampered', form: form(20),
    actions: { prayerCount: -5, fastDays: 'x', meditationHours: 0.5,
      met: { theodora: 2, 'Bad Id': 9 }, gifts: { mystical: 'yes' },
      practices: { alms: { count: 3.7, lastDay: 'yesterday' },
        prayer_rope: { count: 99 } } },
    passions: { acedia: { meetings: 1, overcome: 2, captive: 0,
      discerned: true } },
    date: '2026-12-31' },
];

const records = cases.map((c) => ({
  name: c.name,
  form: clone(c.form),
  actions: clone(c.actions),
  passions: clone(c.passions),
  date: c.date,
  md: J.toMarkdown({ form: c.form, actions: c.actions,
    passions: c.passions, passionData,
    now: new Date(`${c.date}T08:00:00Z`) }, A),
}));

fs.writeFileSync(path.join(root, 'godot/tests/journal_fixture.json'),
  JSON.stringify({ note: 'Generated by scripts/godot/make_journal_fixture.js;'
    + ' do not edit.', records }, null, 1) + '\n');
console.log(`journal fixture: ${records.length} pages`);
