'use strict';
// Write godot/tests/hub_fixture.json from public/ludus/ludus-actions.js,
// the reference for the gate rules of the headset hub (HubCore).
// Usage: node scripts/godot/make_hub_fixture.js

const fs = require('fs');
const path = require('path');
const A = require('../../public/ludus/ludus-actions.js');

const root = path.join(__dirname, '..', '..');
const form = (w) => ({ wisdom: w, faith: 1, dexterity: 1, constitution: 1,
  charisma: 1, cunning: 1, erudition: 1 });
// Scenarios climb the ladder step by step, so every branch of the rules
// (form, dialogue, rite, gift, ladder) is exercised.
const steps = [];
let actions = A.normalize({});
const plan = [
  ['check', 1], ['knots', 10], ['check', 4], ['meet', 'theodora'],
  ['check', 4], ['knots', 23], ['meet', 'elder_sergius'], ['check', 6],
  ['meet', 'abba_john'], ['check', 8], ['still', 10], ['check', 10],
  ['gift', 'contemplative', 10], ['check', 10], ['meet', 'sister_catherine'],
  ['still', 20], ['gift', 'mystical', 12], ['check', 12], ['still', 30],
  ['gift', 'apophatic', 14], ['check', 14], ['check', 3],
  ['fast', 'bad-day'], ['fast', '2026-09-30'], ['fast', '2026-09-30'],
  ['check', 8], ['fast', '2026-10-01'], ['check', 8],
];
plan.forEach(([op, a, b]) => {
  if (op === 'knots') {
    for (let i = 0; i < a; i++) {
      actions = A.prayKnot(actions);
    }
  } else if (op === 'meet') {
    actions = A.recordMeeting(actions, a);
  } else if (op === 'still') {
    actions = A.addStillness(actions, a);
  } else if (op === 'fast') {
    actions = A.keepFast(actions, a);
  } else if (op === 'gift') {
    actions = A.acceptGift(actions, form(b), a);
  }
  const ladder = op === 'check' ? A.evaluateLadder(form(a), actions)
    .map((c) => ({ id: c.gate.id, open: c.open,
      missing: c.missing.map((m) => m.kind), readyForGift: c.readyForGift }))
    : null;
  steps.push({ op, a: a === undefined ? null : a,
    b: b === undefined ? null : b, ladder, fastDays: actions.fastDays });
});
// The fast is a daily act; the headset has no calendar day yet, so it
// is set directly for the ascetic gate.
fs.writeFileSync(path.join(root, 'godot/tests/hub_fixture.json'),
  JSON.stringify({ note: 'Generated by scripts/godot/make_hub_fixture.js; '
    + 'do not edit.', steps }, null, 1) + '\n');
console.log(`hub fixture: ${steps.length} steps`);
