'use strict';
// Write godot/tests/fixture.json from the JS dive core, so the GDScript
// port (godot/scripts/dive_core.gd) is checked number by number against
// the reference (docs/HLD_HEADSET_BUILD_2026-09-30.md, P0).
// Usage: node scripts/godot/make_fixture.js

const fs = require('fs');
const path = require('path');
const D = require('../../public/ludus/dive/dive-core.js');

const root = path.join(__dirname, '..', '..');
const objects = require(path.join(root,
  'public/ludus/data/lake-objects-99.json')).objects;
const fish = require(path.join(root,
  'public/ludus/data/issyk-kul-fish.json')).fish;

const rngSamples = ['dive:x', 'school:chebak', 'Иссык'].map((seed) => {
  const r = D.rng(seed);
  return { seed, values: [r(), r(), r(), r(), r()] };
});
const schools = D.fishSchools(fish);
const fishSamples = schools.slice(0, 6).map((s) => ({
  id: s.id, at: [0, 3, 17.5].map((t) => D.fishAt(s, 2, t)),
}));
let rov = D.newRov();
const inputs = [];
for (let i = 0; i < 120; i++) {
  inputs.push({ forward: (i % 30) / 30, strafe: i % 7 === 0 ? 0.5 : 0,
    vertical: i < 80 ? -0.8 : 1, turn: i % 11 === 0 ? 0.3 : 0 });
}
inputs.forEach((inp) => { rov = D.stepRov(rov, inp, 0.1); });
const t = D.telemetry(rov);

// A game scenario: rise too fast from 70 m, stop, then cross down.
function scenario() {
  let r = { ...D.newRov(), x: 400, depth: 70 };
  let g = D.newGame();
  const plan = [[{ vertical: 1 }, 50], [{}, 200], [{ vertical: -1 }, 30],
    [{ vertical: 1 }, 80], [{ vertical: -1 }, 400]];
  const said = [];
  plan.forEach(([inp, steps]) => {
    for (let i = 0; i < steps; i++) {
      r = D.stepRov(r, { ...inp, drift: D.current(r.x, i * 0.1) }, 0.1);
      const out = D.stepGame(g, r, 0.1, { handedOver: 0 });
      g = out.game;
      said.push(...out.say);
    }
  });
  return { done: g.done, fallen: g.fallen, said: said.length,
    depth: r.depth, z: r.z };
}

// The tether: a full turn and a bit, the same way back, then the arm.
function tetherScenario() {
  let r = { ...D.newRov(), depth: 4 };
  let g = D.newGame();
  const said = [];
  const plan = [[{ turn: 1 }, 84, false], [{ turn: -1 }, 84, false],
    [{}, 1, true], [{ turn: 1 }, 220, false]];
  plan.forEach(([inp, steps, arm]) => {
    for (let i = 0; i < steps; i++) {
      r = D.stepRov(r, inp, 0.1);
      const out = D.stepGame(g, r, 0.1, { handedOver: 0, arm });
      g = out.game;
      said.push(...out.say);
    }
  });
  return { done: g.done, turns: g.turns, wound: g.wound, said: said.length,
    yaw: r.yaw };
}

const fixture = {
  game: scenario(),
  tether: tetherScenario(),
  note: 'Generated by scripts/godot/make_fixture.js; do not edit.',
  rng: rngSamples,
  floor: [0, 35, 160, 245, 333.3, 690].map((x) => ({ x,
    base: D.baseDepth(x), floor: D.floorDepth(x, 12.5) })),
  xForDepth: [0, 5, 20, 37, 90, 160].map((d) => ({ d, x: D.xForDepth(d) })),
  temperature: [0, 40, 50, 60, 150].map((d) => ({ d,
    t: D.temperature(d) })),
  placed: D.placeObjects(objects).map((p) => ({ id: p.id, x: p.x, z: p.z,
    depth: p.depth, yaw: p.yaw, where: p.where })),
  schools: schools.map((s) => ({ id: s.id, centre: s.centre,
    radius: s.radius, count: s.count, phase: s.phase })),
  fishAt: fishSamples,
  rov: { inputs, final: { x: rov.x, z: rov.z, depth: rov.depth,
    yaw: rov.yaw, battery: rov.battery },
  telemetry: { temperature: t.temperature, ascentMPerMin: t.ascentMPerMin,
    echoDelay: t.echoDelay, soundSpeed: t.soundSpeed } },
};
fs.writeFileSync(path.join(root, 'godot/tests/fixture.json'),
  JSON.stringify(fixture, null, 1) + '\n');
console.log(`fixture: ${fixture.placed.length} objects, `
  + `${fixture.schools.length} schools`);
