'use strict';
// Write godot/tests/trial_fixture.json from public/ludus/ludus-missions.js:
// the thresholds of the gates (trialView, chooseTrial) and the fall they
// can lead to (fallStatus, liftFall), the reference for TrialCore.
// Each record keeps its inputs (state, gate, option, form, actions), so
// the GDScript side replays the very same calls.
// Usage: node scripts/godot/make_trial_fixture.js

const fs = require('fs');
const path = require('path');
const M = require('../../public/ludus/ludus-missions.js');
const A = require('../../public/ludus/ludus-actions.js');

const root = path.join(__dirname, '..', '..');
const data = (name) => require(path.join(root, 'public/ludus/data', name));
const ctx = {
  spine: data('campaign-spine.json'),
  trials: data('gate-trials.json'),
  trees: data('dialogue-trees.json'),
  lake: data('lake-objects-99.json'),
  passions: data('passions.json'),
  actionsApi: A,
};
const form = (w) => ({ wisdom: w, faith: 1, dexterity: 1, constitution: 1,
  charisma: 1, cunning: 1, erudition: 1 });
const clone = (o) => JSON.parse(JSON.stringify(o));

// Actions that open every gate up to the apophatic one.
function openAll() {
  let a = A.normalize({});
  for (let i = 0; i < 33; i++) {
    a = A.prayKnot(a);
  }
  ['theodora', 'elder_sergius', 'abba_john', 'sister_catherine']
    .forEach((m) => { a = A.recordMeeting(a, m); });
  a.fastDays = 1;
  a = A.addStillness(a, 60);
  ['contemplative', 'mystical', 'apophatic'].forEach((g) => {
    a = A.acceptGift(a, form(14), g);
  });
  return a;
}

const view = (tv) => (tv ? { open: tv.open, passed: tv.passed,
  waiting: tv.waiting, disabled: tv.options.map((o) => o.disabled) } : null);
const status = (fs_) => ({ fallen: fs_.fallen, passion: fs_.passion || null,
  teacher: fs_.teacher || null, sober: Boolean(fs_.sober),
  taught: Boolean(fs_.taught), canLift: Boolean(fs_.canLift) });

const records = [];
function record(op, st, gateId, optionId, f, a) {
  const input = { op, state: clone(st), gateId, optionId, form: clone(f),
    actions: clone(a) };
  let out;
  if (op === 'view') {
    out = { view: view(M.trialView(ctx, st, gateId, f, a)) };
  } else if (op === 'choose') {
    const res = M.chooseTrial(ctx, st, gateId, optionId, f, a);
    out = { outcome: res.outcome, reply: res.reply,
      state: { trials: res.state.trials, trialWait: res.state.trialWait,
        fall: res.state.fall } };
    st = res.state;
  } else if (op === 'status') {
    out = { status: status(M.fallStatus(ctx, st, a)) };
  } else {
    st = M.liftFall(ctx, st, a);
    out = { state: { trials: st.trials, trialWait: st.trialWait,
      fall: st.fall } };
  }
  records.push({ ...input, out });
  return st;
}

// A closed gate: nothing can be chosen.
let st = M.emptyState();
record('view', st, 'foundational', null, form(1), A.normalize({}));
record('choose', st, 'foundational', 'rock', form(1), A.normalize({}));

// Every gate, every option, from a fresh state with all gates open.
const all = openAll();
ctx.trials.trials.forEach((t) => {
  t.options.forEach((o) => {
    let s = M.emptyState();
    let a = clone(all);
    s = record('view', s, t.gateId, null, form(14), a);
    s = record('choose', s, t.gateId, o.id, form(14), a);
    s = record('view', s, t.gateId, null, form(14), a);
    if (o.outcome === 'return') {
      // Waiting ends with a new talk with the mentor.
      a = A.recordMeeting(a, t.mentor);
      s = record('view', s, t.gateId, null, form(14), a);
    }
    if (o.outcome === 'fall') {
      s = record('status', s, null, null, form(14), a);
      s = record('lift', s, null, null, form(14), a);
      a = A.addStillness(a, 1);
      s = record('status', s, null, null, form(14), a);
      s = record('lift', s, null, null, form(14), a);
      const p = ctx.passions.passions.find((x) => x.id === o.passion);
      a = A.recordMeeting(a, p ? p.teacher : 'elder_sergius');
      s = record('status', s, null, null, form(14), a);
      s = record('lift', s, null, null, form(14), a);
      s = record('status', s, null, null, form(14), a);
    }
  });
});

fs.writeFileSync(path.join(root, 'godot/tests/trial_fixture.json'),
  JSON.stringify({ note: 'Generated by scripts/godot/make_trial_fixture.js;'
    + ' do not edit.', records }, null, 1) + '\n');
console.log(`trial fixture: ${records.length} records`);
