"""Write the licence register and per-object claim sheets.

Step three of the raw-material pipeline (CLAUDE.md, TABOO 0.4).  Every
accepted object gets an entry in THIRD_PARTY_NOTICES.md and a claim sheet
in the style of a Russian utility claim ("отличающийся тем, что"), so the
lawyer reviews one file per object instead of reconstructing history.

Usage:
    python3 scripts/raw_assets/register.py --derived build/derived
"""

import argparse
import json
from pathlib import Path

NOTICE_HEADER = """# Third-party raw material register

Generated by `scripts/raw_assets/register.py`.  Each derived object keeps
the obligations of its source licence (attribution; share-alike for
CC-BY-SA; source availability for GPL).  The 35 % change threshold is an
internal technology rule and does not by itself remove these duties.

| Object | Source | Commit | Path | Licence | Colour | Shape |
|--------|--------|--------|------|---------|-------|-----------|
"""


def claim_text(record):
    """Compose the claim sheet for one derived object."""
    feats = record['features']
    distinguishing = ';\n    '.join(feats[:3])
    evidence = '\n'.join(f'- {f}' for f in feats[3:])
    return f"""# Формула: объект {record['id']}

1. Графический объект игры Ludus, полученный из исходного изображения
   путём переработки, отличающийся тем, что содержит:
    {distinguishing}.

2. Объект по п. 1, отличающийся тем, что изменение цвета объекта и
   изменение его формы (1 - IoU силуэтов) составляют каждое не менее
   35 % при сравнении на общем холсте 256×256.

Доказательная база:
{evidence}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--derived', default='build/derived')
    parser.add_argument('--notices', default='THIRD_PARTY_NOTICES.md')
    args = parser.parse_args()

    derived = Path(args.derived)
    report = json.loads((derived / 'report.json').read_text('utf-8'))
    claims = derived / 'claims'
    claims.mkdir(exist_ok=True)

    rows = []
    for rec in report['accepted']:
        (claims / f'{rec["id"]}.md').write_text(claim_text(rec), 'utf-8')
        rows.append(
            f'| {rec["file"]} | {rec["repo"]} | {rec["commit"][:10]} '
            f'| {rec["path"]} | {rec["license"]} '
            f'| {rec["colour_change"]:.1%} | {rec["shape_change"]:.1%} |')

    Path(args.notices).write_text(NOTICE_HEADER + '\n'.join(rows) + '\n',
                                  encoding='utf-8')
    print(f'{len(rows)} objects registered -> {args.notices}; '
          f'claims in {claims}')


if __name__ == '__main__':
    main()
