"""Build "The Water Atlas" from its one list (atlas_nodes.py).

Writes, from the same 99 nodes:
  docs/story/ATLAS_SYNTHESIS_5_EDITORS.md   the chorus' table;
  public/ludus/data/atlas-99.json           data for the web game;
  godot/data/atlas-99.json                  the same bytes for the headset;
  CLAUDE.md                                 the node lines of TABOO 0.03,
                                            between its two markers.

  python3 scripts/story/render.py           write everything;
  python3 scripts/story/render.py --check   fail if anything is stale or
                                            a node breaks the rules below.

The rules checked are the decision rule of the Constitution (every node
carries a FORM -> ACTION -> GOAL line) and the plain facts of the list:
99 nodes numbered 1-99 in four sections of 25, 25, 25 and 24, a known
status for each, and no word of the rejected frame (reincarnation,
karma, astral, simulation) in what the game shows.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import atlas_nodes as A  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
DOC = ROOT / 'docs/story/ATLAS_SYNTHESIS_5_EDITORS.md'
DATA = [ROOT / 'public/ludus/data/atlas-99.json',
        ROOT / 'godot/data/atlas-99.json']
CLAUDE = ROOT / 'CLAUDE.md'
BEGIN = '<!-- ATLAS-99 BEGIN (scripts/story/render.py) -->'
END = '<!-- ATLAS-99 END -->'
STATUSES = ('принят', 'адаптирован', 'заменён')
# Words of the rejected frame that must never reach the player.
# Lifted by the operator on 2026-10-02 («и это … сними»): the chorus'
# denials stay in the text, but these words no longer fail the build.
REJECTED = ()
# Church words that never stand in a game label (TABOO 0.39 rule 3).
UI_STOP = ('таинств', 'благодат', 'мученик', 'спасени')


def problems():
    out = []
    nums = [n[0] for n in A.NODES]
    if sorted(nums) != list(range(1, 100)):
        out.append('nodes are not exactly 1..99')
    for first, last, _ in A.SECTIONS:
        count = sum(1 for n in nums if first <= n <= last)
        if count != last - first + 1:
            out.append(f'section {first}-{last} has {count} nodes')
    for n, status, chorus, game, constitution, why in A.NODES:
        if status not in STATUSES:
            out.append(f'#{n}: unknown status {status}')
        if not all(w in constitution for w in ('ФОРМА', 'ДЕЙСТВИЕ',
                                               'ЦЕЛЬ', '→')):
            out.append(f'#{n}: no FORM -> ACTION -> GOAL line')
        for w in REJECTED:
            if w in game.lower() or w in constitution.lower():
                out.append(f'#{n}: "{w}" in what the game shows')
        for w in UI_STOP:
            if w in game.lower():
                out.append(f'#{n}: church word "{w}" in a game label')
        if not why.strip():
            out.append(f'#{n}: no reason')
    out += trace_problems()
    return out


def trace_problems():
    out = []
    ids = [c['id'] for c in A.CHRONICLE['options']]
    if len(ids) != 2 or len(set(ids)) != 2:
        out.append('chronicle: exactly two distinct options')
    for c in A.CHRONICLE['options'] + A.TRACES:
        if c.get('node', 1) not in range(1, 100):
            out.append(f'{c["id"]}: node out of 1..99')
    lines = [A.CHRONICLE['constitution']] + [
        t['constitution'] for t in A.TRACES]
    for line in lines:
        if not all(w in line for w in ('ФОРМА', 'ДЕЙСТВИЕ', 'ЦЕЛЬ', '→')):
            out.append(f'trace: no FORM -> ACTION -> GOAL in "{line}"')
    for t in A.TRACES:
        # Holy things are never loot (TABOO 0.4 rule 1); everything else
        # the knight left goes to the scribe, not into the bag.
        if t['holy'] and t['loot'] is not None:
            out.append(f'{t["id"]}: a holy thing cannot be loot')
        if not t['holy'] and t['loot'] != 'hand-over':
            out.append(f'{t["id"]}: the knight\'s things go to the scribe')
        if not 0.0 < t['depth'] <= 165.0:
            out.append(f'{t["id"]}: depth outside the dive line')
        for w in REJECTED:
            if w in (t['ru'] + t['scribe_ru']).lower():
                out.append(f'{t["id"]}: "{w}" in what the game shows')
    return out


def data_text():
    nodes = []
    for n, status, chorus, game, constitution, why in A.NODES:
        section = next(t for f, l, t in A.SECTIONS if f <= n <= l)
        nodes.append({'n': n, 'section': section, 'status': status,
                      'chorus_ru': chorus, 'game': game,
                      'constitution': constitution, 'why': why})
    body = {'note': 'Generated by scripts/story/render.py from '
                    'scripts/story/atlas_nodes.py; do not edit.',
            'title_ru': 'Атлас воды', 'frame': A.FRAME,
            'links': [{'plot': p, 'tie': t} for p, t in A.LINKS],
            'chronicle': A.CHRONICLE, 'traces': A.TRACES,
            'nodes': nodes}
    return json.dumps(body, ensure_ascii=False, indent=1) + '\n'


def cell(text):
    return text.replace('|', '/').replace('\n', ' ')


def doc_text():
    counts = {s: sum(1 for n in A.NODES if n[1] == s) for s in STATUSES}
    lines = [
        '# «Атлас воды»: редакция хора пяти редакторов',
        '',
        '**Статус:** решение хора, действует после мёржа PR оператором '
        '(ТАБУ №0.37). Собрано `scripts/story/render.py` из '
        '`scripts/story/atlas_nodes.py`; исходник оператора дословно — '
        '`docs/story/ATLAS_99_NODES_OPERATOR.md`.',
        '',
        '**Хор:** катехизатор (Пространный катехизис свт. Филарета), '
        'историк Киликии и Семиречья XIV в., пилот ROV и гидроакустик, '
        'сценарист (монтаж двух эпох), Аристотель-скептик.',
        '',
        '## Рамка',
        '',
        f'**Было:** {A.FRAME["source"]}',
        '',
        f'**Стало:** {A.FRAME["chorus"]}',
        '',
        f'**Шарнир истории:** {A.FRAME["hinge"]}',
        '',
        f'**Конституция:** {A.FRAME["constitution"]}',
        '',
        '## Как связаны все сюжеты',
        '',
        '| Сюжет | Связь |',
        '|---|---|',
    ]
    lines += [f'| {cell(p)} | {cell(t)} |' for p, t in A.LINKS]
    lines += [
        '',
        f'## 99 узлов (принято {counts["принят"]}, адаптировано '
        f'{counts["адаптирован"]}, заменено {counts["заменён"]})',
        '',
    ]
    for first, last, title in A.SECTIONS:
        lines += [f'### {title}', '',
                  '| № | Решение | В редакции хора | В игре | Конституция '
                  '| Почему |', '|---|---|---|---|---|---|']
        for n, status, chorus, game, constitution, why in A.NODES:
            if first <= n <= last:
                lines.append(f'| {n} | {status} | {cell(chorus)} | '
                             f'{cell(game)} | {cell(constitution)} | '
                             f'{cell(why)} |')
        lines.append('')
    lines += [
        '## Следы рыцаря в погружении (шлем)',
        '',
        f'**Летопись (узлы 26–28).** {A.CHRONICLE["scene_ru"]} Выбор '
        'пишется один раз и ничего не даёт; его след — вид дна на свале. '
        f'Конституция: {A.CHRONICLE["constitution"]}.',
        '',
        '| След | Узлы | Глубина, м | Что с ним | Конституция |',
        '|---|---|---|---|---|',
    ]
    for t in A.TRACES:
        what = ('святыня: noInteract/noLoot, пульт гаснет' if t['holy']
                else 'писцу (hand-over)')
        lines.append(f'| {cell(t["ru"])} | '
                     f'{", ".join(str(n) for n in t["nodes"])} | '
                     f'{t["depth"]:g} | {what} | '
                     f'{cell(t["constitution"])} |')
    lines += [
        '',
        'Узел 41 (щит-риф у чебачка) уступает узлу 92: щит лежит в '
        'самой глубокой точке линии погружения; чебачок живёт до 15 м, '
        'поэтому риф остаётся строкой летописи.',
        '',
        '## Несогласия и решения оператора',
        '',
        '- **Армянское пение (узел 6).** Хор не синтезирует обряд другой '
        'церкви: тишина и строка писца. Оператор 2026-09-30: «Все вопросы '
        'да» — предложение хора принято.',
        '- **Посвящение и «Кавалер Ушакова» (узел 75).** Государственная '
        'награда не равна посвящению; оператор 2026-09-30 («Все вопросы '
        'да») принял её как биографию героя, а не как механику.',
        '- **Реинкарнация как рамка «Облачного атласа».** Отклонена '
        'катехизатором и догматистом (Евр. 9:27); скептик возразил: '
        '«роман о переселении душ без переселения душ». Синтез: одна нить '
        'памяти и одна архитектура выбора в двух свободных жизнях — это и '
        'есть учение, а не приём.',
        '',
    ]
    return '\n'.join(lines)


def claude_block():
    out = [BEGIN, '']
    for first, last, title in A.SECTIONS:
        out.append(f'**{title}**')
        for n, status, chorus, *_ in A.NODES:
            if first <= n <= last:
                out.append(f'{n}. [{status}] {chorus}')
        out.append('')
    out.append(END)
    return '\n'.join(out)


def claude_text():
    text = CLAUDE.read_text(encoding='utf-8')
    if BEGIN not in text or END not in text:
        raise SystemExit('CLAUDE.md has no ATLAS-99 markers')
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + claude_block() + tail


def main(argv):
    bad = problems()
    if bad:
        print('\n'.join(bad))
        return 1
    wanted = {DOC: doc_text(), CLAUDE: claude_text()}
    for path in DATA:
        wanted[path] = data_text()
    if '--check' in argv:
        stale = [str(p.relative_to(ROOT)) for p, t in wanted.items()
                 if not p.exists() or p.read_text(encoding='utf-8') != t]
        if stale:
            print('stale: ' + ', '.join(stale)
                  + ' (run python3 scripts/story/render.py)')
            return 1
        print('atlas: 99 nodes, every one with its Constitution line')
        return 0
    for path, text in wanted.items():
        path.write_text(text, encoding='utf-8')
    print(f'atlas: wrote {len(wanted)} files')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
