## "The Water Atlas" read at the lectern of the scriptorium (CLAUDE.md
## TABOO 0.03).  Page 0 is the frame and the hinge of history (the
## Catalan Atlas, 1375); pages 1-99 are the nodes in the chorus'
## wording, from godot/data/atlas-99.json (generated by
## scripts/story/render.py, the same bytes as the web game's copy).
## Reading gives nothing: no attribute, no counter (Constitution: the
## goal of reading is the reading).
class_name AtlasCore
extends RefCounted


static func load_data() -> Dictionary:
	return JSON.parse_string(FileAccess.get_file_as_string(
		"res://data/atlas-99.json"))


## scribe: the scribe's page about the things handed over from the lake
## (AtlasTraces.scribe_page); when there is one it follows node 99.
static func page_count(data: Dictionary, scribe := "") -> int:
	return data.nodes.size() + 1 + (1 if scribe != "" else 0)


## The next page after `page`, round to the frame after the last one.
static func next_page(data: Dictionary, page: int, scribe := "") -> int:
	return posmod(page + 1, page_count(data, scribe))


static func page_text(data: Dictionary, page: int, scribe := "") -> String:
	if scribe != "" and page == data.nodes.size() + 1:
		return scribe
	if page <= 0:
		return "%s\n\n%s\n\n%s" % [data.title_ru, data.frame.hinge,
			data.frame.chorus]
	var node: Dictionary = data.nodes[page - 1]
	return "%s\n\n%d. %s" % [node.section, int(node.n), node.chorus_ru]
